development:
  FB_ID: "506103976244859"
  FB_SECRET: "87da04d29c3aabffc3ae045ea05b26cd"

  GOOGLE_API_SERVER_KEY: AIzaSyC0YkV5-vKFV0Pa2_QDbnCrsyw4wEyQVdI
  GOOGLE_API_BROWSER_KEY: AIzaSyDXeZ0r-2NvpMOI0iaebvKbSRlDA6Q9DzY
